name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Prinet Github Repository Name
        run: echo "${{ github.repository }}"
      - name: list all files
        run: ls
      - name: Print goodbye
        run: echo "Done - bye!"
