name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Prinet greeting
        run: echo "Hellow world!"
      - name: Print goodbye
        run: echo "Done - bye!"
